// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_dRidAhP6gT1d5ZHDRTZAGHaesSJWuE',
    appId: '1:793187527934:web:7d65a2a869e4f4199cc9af',
    messagingSenderId: '793187527934',
    projectId: 'doctors-appointment-admin',
    authDomain: 'doctors-appointment-admin.firebaseapp.com',
    storageBucket: 'doctors-appointment-admin.appspot.com',
    measurementId: 'G-R62K1Z2QHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZw06gFU3mbvXTgZh55MmzTg_brivMlEI',
    appId: '1:793187527934:android:1b5f50230d7904ce9cc9af',
    messagingSenderId: '793187527934',
    projectId: 'doctors-appointment-admin',
    storageBucket: 'doctors-appointment-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0dTX-V8uyLTZ_daM5oM-ewoyVbNIJA4',
    appId: '1:793187527934:ios:abdf12bf13bf4c449cc9af',
    messagingSenderId: '793187527934',
    projectId: 'doctors-appointment-admin',
    storageBucket: 'doctors-appointment-admin.appspot.com',
    iosClientId: '793187527934-sb6n5qeahlicq70jj6n2kq1d8f93k9kg.apps.googleusercontent.com',
    iosBundleId: 'com.fusionTeck.smartDoctor',
  );
}
